import { StyleSheet } from 'react-native';
import { getShadowStyle, palette, radius } from '@/theme';

// Shared by the Deliverables list (DeliverablesScreen.tsx) and one piece's
// screen (DeliverablePieceScreen.tsx). Content uses layoutStyle.scrollContent's
// 16px gutter; sections are separated by `gap`, like the Offer screen.
export const deliverablesStyle = StyleSheet.create({
  headerGap: { marginBottom: 8 },
  content: { gap: 16, paddingBottom: 24 },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  title: { flex: 1, fontSize: 20, lineHeight: 28, fontWeight: '600' },
  linkText: { fontSize: 14, lineHeight: 21, fontWeight: '600', color: palette.primary[500] },

  // --- Deliverables list (DeliverablesScreen.tsx) ---
  // Brand-gradient summary card: title, content deadline, approval progress.
  hero: {
    borderRadius: radius.xl,
    padding: 20,
    gap: 12,
    overflow: 'hidden',
    ...getShadowStyle('md'),
  },
  heroGlow: {
    position: 'absolute',
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  heroGlowSmall: {
    position: 'absolute',
    bottom: -30,
    left: -20,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  heroTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  heroEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 1.2,
    color: 'rgba(255, 255, 255, 0.75)',
  },
  heroStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  heroStatusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: palette.warning[300] },
  heroStatusDotDone: { backgroundColor: palette.success[300] },
  heroStatusText: { fontSize: 12, lineHeight: 16, fontWeight: '600', color: palette.white },
  heroTitle: { fontSize: 22, lineHeight: 30, fontWeight: '700', color: palette.white },
  heroMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  heroMeta: { fontSize: 14, lineHeight: 20, color: palette.primary[50] },
  progressBlock: { gap: 8, marginTop: 4 },
  progressLabels: { flexDirection: 'row', justifyContent: 'space-between' },
  progressLabel: { fontSize: 13, lineHeight: 18, color: 'rgba(255, 255, 255, 0.8)' },
  progressValue: { fontSize: 13, lineHeight: 18, fontWeight: '600', color: palette.white },
  progressTrack: {
    height: 8,
    borderRadius: radius.full,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  progressFill: { height: '100%', borderRadius: radius.full, backgroundColor: palette.white },
  // "View campaign" / "View agreement" - two pills, half the row each (a lone
  // pill keeps half width too).
  pillRow: { flexDirection: 'row', gap: 12 },
  pillButton: {
    flexBasis: 0,
    flexGrow: 1,
    maxWidth: '50%',
    height: 44,
    flexDirection: 'row',
    gap: 8,
    borderRadius: radius.full,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    ...getShadowStyle('xs'),
  },
  pillButtonPressed: { backgroundColor: palette.primary[25], borderColor: palette.primary[200] },
  pillText: { fontSize: 14, lineHeight: 20, fontWeight: '600', color: palette.primary[500] },
  bannerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  bannerText: { flex: 1 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
  countChip: {
    minWidth: 24,
    height: 24,
    borderRadius: radius.full,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[50],
  },
  countChipText: { fontSize: 12, fontWeight: '700', color: palette.primary[600] },
  pieceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderRadius: radius.xl,
    padding: 14,
    ...getShadowStyle('sm'),
  },
  pieceCardOverdue: { borderColor: palette.error[200] },
  pieceCardPressed: { opacity: 0.85, transform: [{ scale: 0.99 }] },
  platformIcon: {
    width: 44,
    height: 44,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[25],
  },
  pieceBody: { flex: 1, gap: 4 },
  pieceTitle: { fontSize: 15, lineHeight: 22, fontWeight: '600' },
  pieceMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pieceAside: { alignItems: 'flex-end', gap: 8 },
  emptyCard: {
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: radius.xl,
    paddingVertical: 28,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[50],
  },
  emptyText: { textAlign: 'center' },

  // --- Shared ---
  sectionTitle: { fontSize: 16, lineHeight: 24, fontWeight: '600' },
  hintText: { fontSize: 14, lineHeight: 21 },
  banner: {
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  successBanner: { backgroundColor: palette.success[50] },
  successText: { color: palette.success[700], fontSize: 14, lineHeight: 21, fontWeight: '500' },
  warningBanner: { backgroundColor: palette.warning[50] },
  warningText: { color: palette.warning[700], fontSize: 14, lineHeight: 21 },
  errorBanner: { backgroundColor: palette.error[50] },
  errorText: { color: palette.error[700], fontSize: 14, lineHeight: 21 },
  rowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  meta: { fontSize: 13, lineHeight: 19 },
  overdue: { color: palette.error[600], fontWeight: '600' },
  form: {
    borderWidth: 1,
    borderRadius: radius.md,
    padding: 16,
    gap: 12,
  },
  toggle: { flexDirection: 'row', gap: 8 },
  toggleOption: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 999,
    paddingVertical: 8,
    alignItems: 'center',
  },
  toggleOptionActive: {
    backgroundColor: palette.primary[25],
    borderColor: palette.primary[500],
  },
  toggleText: { fontSize: 14, fontWeight: '600' },
  pickButton: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: radius.md,
    paddingVertical: 16,
    alignItems: 'center',
    gap: 8,
  },
  thumbnail: { width: 96, height: 96, borderRadius: radius.md },
  fieldError: { color: palette.error[600], fontSize: 12, lineHeight: 18 },
  multiline: { minHeight: 88, textAlignVertical: 'top' },
  primaryButton: { backgroundColor: palette.primary[500], borderRadius: 999 },
  primaryTitle: { color: palette.white, fontWeight: '600' },
  historyItem: {
    borderWidth: 1,
    borderRadius: radius.md,
    padding: 12,
    gap: 4,
  },
  lateTag: {
    alignSelf: 'flex-start',
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: '500',
    color: palette.error[700],
    backgroundColor: palette.error[50],
  },
  reviewBox: {
    borderRadius: radius.sm,
    padding: 8,
    backgroundColor: palette.gray[25],
  },
});
