import { StyleSheet } from 'react-native';
import { getShadowStyle, palette, radius } from '@/theme';

// One deliverable piece (DeliverablePieceScreen.tsx). Same visual language as
// the Deliverables list: a brand-gradient summary card, rounded elevated
// cards, icon tiles and pill buttons. Content uses layoutStyle.scrollContent's
// 16px gutter; sections are separated by `gap`.
export const pieceStyle = StyleSheet.create({
  headerGap: { marginBottom: 8 },
  content: { gap: 16, paddingBottom: 32 },
  hintText: { fontSize: 14, lineHeight: 21 },

  // --- Summary card ---
  hero: {
    borderRadius: radius.xl,
    padding: 20,
    gap: 14,
    overflow: 'hidden',
    ...getShadowStyle('md'),
  },
  heroGlow: {
    position: 'absolute',
    top: -60,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  heroGlowSmall: {
    position: 'absolute',
    bottom: -30,
    left: -20,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  heroTopRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  heroIcon: {
    width: 48,
    height: 48,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  heroTitleBlock: { flex: 1, gap: 2 },
  heroEyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 1.2,
    color: 'rgba(255, 255, 255, 0.75)',
  },
  heroTitle: { fontSize: 20, lineHeight: 28, fontWeight: '700', color: palette.white },
  heroChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  heroChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  heroChipDanger: { backgroundColor: palette.error[500] },
  heroChipText: { fontSize: 12, lineHeight: 16, fontWeight: '600', color: palette.white },

  // --- Notices ---
  notice: {
    flexDirection: 'row',
    gap: 12,
    borderRadius: radius.lg,
    padding: 14,
  },
  noticeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeBody: { flex: 1, gap: 2 },
  noticeTitle: { fontSize: 14, lineHeight: 20, fontWeight: '700' },
  noticeText: { fontSize: 14, lineHeight: 20 },
  warningNotice: { backgroundColor: palette.warning[50] },
  warningIcon: { backgroundColor: palette.warning[100] },
  warningText: { color: palette.warning[700] },
  errorNotice: { backgroundColor: palette.error[50] },
  errorIcon: { backgroundColor: palette.error[100] },
  errorText: { color: palette.error[700] },
  successNotice: { backgroundColor: palette.success[50] },
  successIcon: { backgroundColor: palette.success[100] },
  successText: { color: palette.success[700] },
  neutralNotice: { backgroundColor: palette.gray[25] },
  neutralIcon: { backgroundColor: palette.gray[50] },
  neutralText: { color: palette.gray[500] },

  // --- Form cards ---
  card: {
    borderWidth: 1,
    borderRadius: radius.xl,
    padding: 16,
    gap: 14,
    ...getShadowStyle('sm'),
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  cardIcon: {
    width: 40,
    height: 40,
    borderRadius: radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[25],
  },
  cardHeaderText: { flex: 1, gap: 2 },
  cardTitle: { fontSize: 16, lineHeight: 22, fontWeight: '700' },
  cardSubtitle: { fontSize: 13, lineHeight: 18 },
  segmented: {
    flexDirection: 'row',
    borderRadius: radius.full,
    padding: 4,
    gap: 4,
  },
  segment: {
    flex: 1,
    height: 40,
    flexDirection: 'row',
    gap: 6,
    borderRadius: radius.full,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentActive: { backgroundColor: palette.white, ...getShadowStyle('xs') },
  segmentText: { fontSize: 14, fontWeight: '600' },
  segmentTextActive: { color: palette.primary[500] },
  dropzone: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderRadius: radius.xl,
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 8,
  },
  dropzoneError: { borderColor: palette.error[400], backgroundColor: palette.error[25] },
  dropzoneIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[50],
  },
  dropzoneTitle: { fontSize: 15, lineHeight: 22, fontWeight: '600' },
  dropzoneHint: { fontSize: 12, lineHeight: 17, textAlign: 'center' },
  preview: { borderRadius: radius.xl, overflow: 'hidden' },
  previewImage: { width: '100%', height: 200 },
  previewActions: {
    position: 'absolute',
    right: 10,
    top: 10,
    flexDirection: 'row',
    gap: 8,
  },
  previewAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.full,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(16, 24, 40, 0.65)',
  },
  previewActionText: { fontSize: 12, fontWeight: '600', color: palette.white },
  fieldError: { color: palette.error[600], fontSize: 12, lineHeight: 18 },
  multiline: { minHeight: 96, textAlignVertical: 'top' },
  counter: { alignSelf: 'flex-end', fontSize: 12, lineHeight: 16, marginTop: -8 },
  counterOver: { color: palette.error[600], fontWeight: '600' },
  formBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: radius.lg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  formBannerText: { flex: 1, fontSize: 14, lineHeight: 20 },
  primaryButton: {
    height: 52,
    borderRadius: radius.full,
    backgroundColor: palette.primary[500],
    ...getShadowStyle('sm'),
  },
  primaryTitle: { fontSize: 16, fontWeight: '700', color: palette.white },

  // --- Submission timeline ---
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontSize: 16, lineHeight: 24, fontWeight: '700' },
  countChip: {
    minWidth: 24,
    height: 24,
    borderRadius: radius.full,
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[50],
  },
  countChipText: { fontSize: 12, fontWeight: '700', color: palette.primary[600] },
  timeline: { gap: 0 },
  timelineItem: { flexDirection: 'row', gap: 12 },
  timelineRail: { alignItems: 'center', width: 16 },
  timelineDot: { width: 12, height: 12, borderRadius: 6, marginTop: 18, borderWidth: 2 },
  timelineLine: { flex: 1, width: 2, marginTop: 4 },
  historyCard: {
    flex: 1,
    borderWidth: 1,
    borderRadius: radius.lg,
    padding: 12,
    gap: 8,
    marginBottom: 12,
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  historyTitle: { fontSize: 14, lineHeight: 20, fontWeight: '700' },
  historyDate: { fontSize: 12, lineHeight: 16 },
  historyTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tag: {
    overflow: 'hidden',
    borderRadius: radius.full,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 12,
    fontWeight: '600',
  },
  lateTag: { color: palette.error[700], backgroundColor: palette.error[50] },
  attachment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: palette.gray[25],
  },
  attachmentText: { flex: 1, fontSize: 13, lineHeight: 18 },
  linkText: { color: palette.primary[500], fontWeight: '600' },
  reviewBox: {
    borderLeftWidth: 3,
    borderRadius: radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  reviewApproved: { borderLeftColor: palette.success[500], backgroundColor: palette.success[25] },
  reviewChanges: { borderLeftColor: palette.warning[500], backgroundColor: palette.warning[25] },
  reviewTitle: { fontSize: 13, lineHeight: 18, fontWeight: '700' },
  emptyCard: {
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderRadius: radius.xl,
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.primary[50],
  },
});
